name: Deploy-Live

on:
  push:
    branches:
      - master
      - release/*
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: "actions/checkout@v1"
        with:
          ref: ${{ github.ref }}
      - name: 'cat package.json'
        run: cat ./package.json
      - uses: actions/setup-node@master
        with:
          node-version: '10.x'
      - run: npm install
      - run: npm run generate
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --project recycler-99415
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: 'Automated Version Bump'
        uses: 'phips28/gh-action-bump-version@master'
        with:
          tag-prefix: ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'cat package.json'
        run: cat ./package.json
